
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shavinu
 */
public class FORM_Login_Screen extends javax.swing.JFrame {

    /**
     * Creates new form FORM_Login_Screen
     */
    public FORM_Login_Screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLec = new javax.swing.JButton();
        btnStu = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnNewLec = new javax.swing.JButton();
        btnNewStu = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UniLogy Pioneer Learning Management System by TeamOne");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(500, 80));
        setResizable(false);

        btnLec.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        btnLec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lec.png"))); // NOI18N
        btnLec.setText("Lecturer Login");
        btnLec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLecMouseExited(evt);
            }
        });
        btnLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecActionPerformed(evt);
            }
        });

        btnStu.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        btnStu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stu.png"))); // NOI18N
        btnStu.setText("Student Login");
        btnStu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStuMouseExited(evt);
            }
        });
        btnStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStuActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 3, 36)); // NOI18N
        jLabel1.setText("Unilogy Learning Management System ");

        btnNewLec.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        btnNewLec.setText("I'm a new Lecturer");
        btnNewLec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewLecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewLecMouseExited(evt);
            }
        });
        btnNewLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewLecActionPerformed(evt);
            }
        });

        btnNewStu.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        btnNewStu.setText("I'm a new Student");
        btnNewStu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewStuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewStuMouseExited(evt);
            }
        });
        btnNewStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewStuActionPerformed(evt);
            }
        });

        btnAbout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAbout.setText("About");
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMouseExited(evt);
            }
        });
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(btnNewLec)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNewStu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(112, 112, 112))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(btnLec, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(btnStu, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(130, 130, 130)
                                    .addComponent(jLabel1)))
                            .addGap(28, 28, 28)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLec)
                    .addComponent(btnStu))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewLec, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewStu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStuMouseEntered
        // TODO add your handling code here:
        this.btnStu.setBackground(Color.YELLOW);
    }//GEN-LAST:event_btnStuMouseEntered

    private void btnStuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStuMouseExited
        // TODO add your handling code here:
        this.btnStu.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnStuMouseExited

    private void btnLecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLecMouseEntered
        // TODO add your handling code here:
        this.btnLec.setBackground(Color.YELLOW);
    }//GEN-LAST:event_btnLecMouseEntered

    private void btnLecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLecMouseExited
        // TODO add your handling code here:
        this.btnLec.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnLecMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FORM_Login().setVisible(true);
    }//GEN-LAST:event_btnLecActionPerformed

    private void btnStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FORM_Stu_Login().setVisible(true);
    }//GEN-LAST:event_btnStuActionPerformed

    private void btnNewLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewLecActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FORM_Lec_New().setVisible(true);
    }//GEN-LAST:event_btnNewLecActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
                this.setVisible(false);
        new FORM_Group_Mem().setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnNewStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewStuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FORM_new_Stud().setVisible(true);
    }//GEN-LAST:event_btnNewStuActionPerformed

    private void btnNewLecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewLecMouseEntered
        // TODO add your handling code here:
        this.btnNewLec.setBackground(Color.cyan);
    }//GEN-LAST:event_btnNewLecMouseEntered

    private void btnNewLecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewLecMouseExited
        // TODO add your handling code here:
        this.btnNewLec.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnNewLecMouseExited

    private void btnNewStuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewStuMouseEntered
        // TODO add your handling code here:
        this.btnNewStu.setBackground(Color.cyan);
    }//GEN-LAST:event_btnNewStuMouseEntered

    private void btnNewStuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewStuMouseExited
        // TODO add your handling code here:
        this.btnNewStu.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnNewStuMouseExited

    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        // TODO add your handling code here:
        this.btnAbout.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_btnAboutMouseEntered

    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        // TODO add your handling code here:
        this.btnAbout.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnAboutMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        this.btnExit.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        this.btnExit.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnExitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORM_Login_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORM_Login_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORM_Login_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_Login_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM_Login_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLec;
    private javax.swing.JButton btnNewLec;
    private javax.swing.JButton btnNewStu;
    private javax.swing.JButton btnStu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
