
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shavinu
 */
public class FORM_Stuu extends javax.swing.JFrame {

    /**
     * Creates new form FORM_Stuu
     */
    public FORM_Stuu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnViewC = new javax.swing.JButton();
        btnAddCour = new javax.swing.JButton();
        btnUpAss = new javax.swing.JButton();
        btnMat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome Student");
        setLocation(new java.awt.Point(500, 120));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Welcome ");

        btnViewC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ccc.png"))); // NOI18N
        btnViewC.setText("View Courses");
        btnViewC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewCMouseExited(evt);
            }
        });
        btnViewC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCActionPerformed(evt);
            }
        });

        btnAddCour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddCour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jo.png"))); // NOI18N
        btnAddCour.setText("Join Course");
        btnAddCour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddCourMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddCourMouseExited(evt);
            }
        });
        btnAddCour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourActionPerformed(evt);
            }
        });

        btnUpAss.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpAss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uplo.png"))); // NOI18N
        btnUpAss.setText("Upload Assignment");
        btnUpAss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpAssMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpAssMouseExited(evt);
            }
        });
        btnUpAss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpAssActionPerformed(evt);
            }
        });

        btnMat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mat.png"))); // NOI18N
        btnMat.setText("Materials");
        btnMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMatMouseExited(evt);
            }
        });
        btnMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("Last Login Time : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnViewC, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnAddCour, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnMat, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnUpAss, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddCour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMat, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpAss, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FORM_Login_Screen().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnViewCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewCMouseEntered
        // TODO add your handling code here:
        this.btnViewC.setBackground(Color.cyan);
    }//GEN-LAST:event_btnViewCMouseEntered

    private void btnViewCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewCMouseExited
        // TODO add your handling code here:
        this.btnViewC.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnViewCMouseExited

    private void btnAddCourMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCourMouseEntered
        // TODO add your handling code here:
        this.btnAddCour.setBackground(Color.cyan);
    }//GEN-LAST:event_btnAddCourMouseEntered

    private void btnAddCourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCourMouseExited
        // TODO add your handling code here:
        this.btnAddCour.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnAddCourMouseExited

    private void btnUpAssMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpAssMouseEntered
        // TODO add your handling code here:
        this.btnUpAss.setBackground(Color.cyan);
    }//GEN-LAST:event_btnUpAssMouseEntered

    private void btnUpAssMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpAssMouseExited
        // TODO add your handling code here:
        this.btnUpAss.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnUpAssMouseExited

    private void btnMatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMatMouseEntered
        // TODO add your handling code here:
        this.btnMat.setBackground(Color.cyan);
    }//GEN-LAST:event_btnMatMouseEntered

    private void btnMatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMatMouseExited
        // TODO add your handling code here:
        this.btnMat.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnMatMouseExited

    private void btnViewCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCActionPerformed
        this.setVisible(false);
        View_Courses c = new View_Courses();
        c.setVisible(true);
    }//GEN-LAST:event_btnViewCActionPerformed

    private void btnAddCourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourActionPerformed
        this.setVisible(false);
        Join_Courses c = new Join_Courses();
        c.setVisible(true);;
    }//GEN-LAST:event_btnAddCourActionPerformed

    private void btnMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatActionPerformed
        // TODO add your handling code here:
        Material_Location l = new Material_Location();
        l.setVisible(true);
    }//GEN-LAST:event_btnMatActionPerformed

    private void btnUpAssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpAssActionPerformed
        // TODO add your handling code here:
        FORM_Student_Assign n = new FORM_Student_Assign();
        n.setVisible(true);
    }//GEN-LAST:event_btnUpAssActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Calendar cal = Calendar.getInstance(); 
        cal.getTime(); 
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss"); 
        jLabel2.setText(sdf.format(cal.getTime()));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORM_Stuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORM_Stuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORM_Stuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_Stuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM_Stuu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCour;
    private javax.swing.JButton btnMat;
    private javax.swing.JButton btnUpAss;
    private javax.swing.JButton btnViewC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
