
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.time;
import java.awt.Color;
import java.sql.Date;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shavinu
 */
public class Home_Lectu extends javax.swing.JFrame {

    /**
     * Creates new form Home_Lectu
     */
    public Home_Lectu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCourse = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();
        btnMat = new javax.swing.JButton();
        btnStu = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btnDelMat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome Sir");
        setLocation(new java.awt.Point(500, 120));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Welcome");

        btnCourse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c.png"))); // NOI18N
        btnCourse.setText("Courses");
        btnCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCourseMouseExited(evt);
            }
        });
        btnCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseActionPerformed(evt);
            }
        });

        btnAssign.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAssign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aaa.png"))); // NOI18N
        btnAssign.setText("Assignments");
        btnAssign.setToolTipText("Upload Assignments");
        btnAssign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAssignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAssignMouseExited(evt);
            }
        });
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnMat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mm.png"))); // NOI18N
        btnMat.setText("Materials");
        btnMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMatMouseExited(evt);
            }
        });
        btnMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatActionPerformed(evt);
            }
        });

        btnStu.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnStu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ss.png"))); // NOI18N
        btnStu.setText("View Assignment"); // NOI18N
        btnStu.setToolTipText("View Assignments uploaded by the students");
        btnStu.setActionCommand(" Student Assignment");
        btnStu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStuMouseExited(evt);
            }
        });
        btnStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStuActionPerformed(evt);
            }
        });

        btnReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/re.png"))); // NOI18N
        btnReport.setText("Report");
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
        });
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Log Out");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("Exit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        btnDelMat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ma.png"))); // NOI18N
        btnDelMat.setText("Delete Material");
        btnDelMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDelMatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDelMatMouseExited(evt);
            }
        });
        btnDelMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelMatActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("Last Login Time : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnStu, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnDelMat, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnMat, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(438, 438, 438)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMat, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelMat, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnCourse.getAccessibleContext().setAccessibleName("btnCourse");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseMouseEntered
        // TODO add your handling code here:
        this.btnCourse.setBackground(Color.YELLOW);
    }//GEN-LAST:event_btnCourseMouseEntered

    private void btnCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseMouseExited
        // TODO add your handling code here:
        this.btnCourse.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnCourseMouseExited

    private void btnAssignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssignMouseEntered
        // TODO add your handling code here:
        this.btnAssign.setBackground(Color.YELLOW);
    }//GEN-LAST:event_btnAssignMouseEntered

    private void btnAssignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssignMouseExited
        // TODO add your handling code here:
        this.btnAssign.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnAssignMouseExited

    private void btnMatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMatMouseEntered
        // TODO add your handling code here:
        this.btnMat.setBackground(Color.YELLOW);
    }//GEN-LAST:event_btnMatMouseEntered

    private void btnMatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMatMouseExited
        // TODO add your handling code here:
        this.btnMat.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnMatMouseExited

    private void btnStuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStuMouseEntered
        // TODO add your handling code here:
        this.btnStu.setBackground(Color.YELLOW);
    }//GEN-LAST:event_btnStuMouseEntered

    private void btnStuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStuMouseExited
        // TODO add your handling code here:
        this.btnStu.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnStuMouseExited

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
        // TODO add your handling code here:
        this.btnReport.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnReportMouseExited

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        // TODO add your handling code here:
        this.btnReport.setBackground(Color.YELLOW);
    }//GEN-LAST:event_btnReportMouseEntered

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FORM_Login_Screen m = new FORM_Login_Screen();
        m.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseActionPerformed
        this.setVisible(false); 
        Courses a = new Courses();
        a.setVisible(true);
    }//GEN-LAST:event_btnCourseActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        new FORM_Assignment().setVisible(true);       
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatActionPerformed
        // TODO add your handling code here:
        new Study_Material().setVisible(true);
    }//GEN-LAST:event_btnMatActionPerformed

    private void btnStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStuActionPerformed
        // TODO add your handling code here:
        new Assignment_Location().setVisible (true);
    }//GEN-LAST:event_btnStuActionPerformed

    private void btnDelMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelMatActionPerformed
        // TODO add your handling code here:
        new Frorm_Study_Mat_Delete().setVisible(true);       
    }//GEN-LAST:event_btnDelMatActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        try
        {
            MySqlConnection mysql = new MySqlConnection();
            Class.forName(mysql.MyDriver);
            java.sql.Connection con = DriverManager.getConnection(mysql.Connection,"root","");
            String Report = "C:\\Users\\Shavinu\\Desktop\\FINAL PROJECT\\Learning Management System V.4.0\\src\\Lecture by Course.jrxml";
            JasperReport Jp = JasperCompileManager.compileReport(Report);
            JasperPrint JPri = JasperFillManager.fillReport(Jp, null, con);
            JasperViewer.viewReport(JPri);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_btnReportActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
            //Date d = new Date();
    //SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
    //jLabel1.setText("The current time is "+sdf.format(d));
    
    Calendar cal = Calendar.getInstance(); 
    cal.getTime(); 
    SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss"); 
    jLabel2.setText(sdf.format(cal.getTime()));
    
    
    }//GEN-LAST:event_formWindowOpened

    private void btnDelMatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMatMouseEntered
        // TODO add your handling code here:
        this.btnDelMat.setBackground(Color.YELLOW);
    }//GEN-LAST:event_btnDelMatMouseEntered

    private void btnDelMatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMatMouseExited
        // TODO add your handling code here:
        this.btnDelMat.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnDelMatMouseExited

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Lectu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Lectu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Lectu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Lectu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Lectu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnCourse;
    private javax.swing.JButton btnDelMat;
    private javax.swing.JButton btnMat;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnStu;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
